# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mahen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mahen/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mahen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mahen/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mahen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mahen/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mahen/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mahen/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [11]:
print("%d bytes" % (a.size * a.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
%run `python -c "import numpy; http://numpy.info(numpy.add)"`

SyntaxError: invalid syntax (3524279668.py, line 1)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [27]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [40]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [47]:
a=np.arange(10)
print(a)
b=a[::-1]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [60]:
a= np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [61]:
a=np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [62]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [66]:
a=np.random.random((3,3,3))
print(a)

[[[0.96780137 0.90404399 0.02000833]
  [0.5457005  0.81257375 0.69936624]
  [0.94685686 0.95468967 0.19751683]]

 [[0.6540118  0.55831692 0.96341759]
  [0.78681585 0.52133434 0.0265539 ]
  [0.18321512 0.93984929 0.53398813]]

 [[0.9852841  0.36742042 0.47054224]
  [0.11513281 0.68533509 0.54176453]
  [0.79880455 0.94127459 0.94937627]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [77]:
a=np.random.random((10,10))
print(a)
b= a.min(), a.max()
b

[[0.06413549 0.65250863 0.24026785 0.70496559 0.70792898 0.17299423
  0.07478297 0.81596792 0.18501984 0.88630173]
 [0.80870204 0.27393408 0.31977099 0.2215808  0.31687226 0.54570794
  0.42085025 0.15622539 0.73167674 0.38547375]
 [0.9248272  0.25451923 0.05052726 0.96386399 0.63433396 0.37030997
  0.93857524 0.84618595 0.48378348 0.21586717]
 [0.40939046 0.60165099 0.04555567 0.92417484 0.80994051 0.63669425
  0.55224114 0.94594891 0.61863804 0.26506817]
 [0.64736926 0.33691092 0.82758084 0.74250558 0.53838525 0.72841467
  0.49860269 0.60830745 0.14418304 0.63040242]
 [0.38605907 0.37677228 0.29487071 0.13441431 0.23330454 0.14695321
  0.00249665 0.68777218 0.56554633 0.4675216 ]
 [0.05950544 0.25587056 0.34624076 0.16239007 0.19403316 0.98811151
  0.78879173 0.65645082 0.05831704 0.89923153]
 [0.89361883 0.67737211 0.83407597 0.81819068 0.27901186 0.8886296
  0.78455316 0.29073134 0.09705967 0.63731916]
 [0.682394   0.33823957 0.13580043 0.29806811 0.31319873 0.8448849
  0.10289581 0

(0.0024966498148749627, 0.9881115055962026)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [79]:
a=np.random.random(30)
print(a)
b=a.mean()
b

[0.92388985 0.73426214 0.37245124 0.34235751 0.76281936 0.81970178
 0.34730947 0.81600501 0.941767   0.96868636 0.93405064 0.10600144
 0.61099327 0.66731117 0.11025153 0.77572538 0.58861257 0.33125766
 0.42360024 0.5151359  0.64105023 0.0547971  0.94317116 0.57293916
 0.00832283 0.58730975 0.98657054 0.68322574 0.16429127 0.89789548]


0.5877254264791251

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [85]:
a=np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [115]:
a=np.ones((5,5))
a= np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [116]:
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [117]:
a = np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [118]:
a = np.zeros((8,8),dtype=int)

a[1::2,::2] = 1

a[::2,1::2] = 1

print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [121]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [122]:
np.tile( np.array([[0,1],[1,0]]), (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [125]:
Z = np.random.random((5,5))

Zmax, Zmin = Z.max(), Z.min()

Z = (Z - Zmin)/(Zmax - Zmin)

print(Z)

[[0.44143061 0.09085508 0.09978453 0.06164588 0.20102842]
 [0.78418284 0.         0.40126204 0.38322591 0.582995  ]
 [0.68490363 0.28253367 0.58142361 0.81934655 0.74168597]
 [0.26074193 0.97980992 0.51262086 0.7601275  0.5789129 ]
 [0.61069885 0.68225476 1.         0.45710576 0.93573763]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [126]:
color = np.dtype([("r", np.ubyte, 1),

("g", np.ubyte, 1),

("b", np.ubyte, 1),

("a", np.ubyte, 1)])

C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\2712604900.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [138]:
a=np.ones((5,3))
b=np.ones((3,2))

print(a)
print(b)
c= a@b
print(c)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [143]:
a=np.arange(10)
a[3:9]=np.multiply(a[3:9],-1)
print(a)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [150]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [152]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [165]:
a=np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[-3.  6.  8. -1. -2.  3. -1.  5. -4. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [239]:
a=np.random.randint(0,10,10)
print(a)
b=np.random.randint(0,10,10)
print(b)
print(np.intersect1d(a,b))


[9 8 0 0 7 0 7 9 2 1]
[3 6 0 9 5 4 0 9 8 5]
[0 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [242]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [243]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [249]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today= np.datetime64('today')
print(today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2022-10-31
2022-11-01
2022-11-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [255]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [271]:
A= np.ones(3)*1
B= np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)


array([3., 3., 3.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [310]:
a = np.random.uniform(0,10,10)

print (a - a%1)

print (np.floor(a))

print (np.ceil(a)-1)

print (a.astype(int))

print (np.trunc(a))



[3. 6. 9. 4. 8. 2. 1. 5. 7. 7.]
[3. 6. 9. 4. 8. 2. 1. 5. 7. 7.]
[3. 6. 9. 4. 8. 2. 1. 5. 7. 7.]
[3 6 9 4 8 2 1 5 7 7]
[3. 6. 9. 4. 8. 2. 1. 5. 7. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [316]:
a=np.zeros((5,5))
a+= np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [336]:
import numpy as np
def generate():
    for a in range (10):
        yield a
x=np.fromiter(generate(), dtype=float, count=-1)
print(x)



[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [338]:
a = np.linspace(0,1,11,endpoint=False)[1: ]
print(a)
print(np.floor(a))

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [343]:
a=np.random.random(10)
a.sort()
a

array([0.05622879, 0.41468038, 0.45312886, 0.4629657 , 0.48249486,
       0.60119063, 0.69531578, 0.84540842, 0.92139088, 0.98712648])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [346]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [476]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
c=np.allclose(a,b)
print(c)
d=np.array_equal(a,b)
print(d)
c=np.allclose(a,b)
print(c)
d=np.array_equal(a,b)
print(d)
print(c)
d=np.array_equal(a,b)
print(d)
c=np.allclose(a,b)
print(c)
d=np.array_equal(a,b)
print(d)

False
False
False
False
False
False
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [483]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [496]:
from regex import D


a=np.random.random((10,2))
b,c = a[:,0], a[:,1]
d = np.sqrt(b**2+c**2)
e = np.arctan2(c,b)
print(d)
print(e)


[0.93371555 1.00940725 0.96886026 1.16059886 0.50248015 0.90796597
 0.63628328 0.70091456 0.36749858 0.44293062]
[1.11970607 1.3185311  1.46145437 1.01777496 0.16554136 0.47158904
 0.86614293 0.93599827 0.46587649 0.58247929]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [515]:
a=np.random.random(10)
a[a.argmax()]=0
print(a)


[0.52163767 0.161519   0.35205826 0.47679027 0.43880571 0.5182288
 0.29466271 0.39573776 0.         0.47029146]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [528]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [541]:
a = np.arange(8)
b = a + 0.5
C = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [542]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [546]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [562]:
a = np.arange(100)
print(a)
b = np.random.uniform(0,100)
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
10.256803396172698
10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [564]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\1282658442.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [885]:
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.64285436 0.47667383 0.71819581 1.00703983 0.61249807
  0.36455136 0.48786915 0.90168744 0.04086919]
 [0.64285436 0.         0.17323796 0.77744362 0.88769938 0.22558968
  0.52223785 0.71179247 0.30288854 0.61633727]
 [0.47667383 0.17323796 0.         0.66829804 0.83388421 0.2751683
  0.42789747 0.56430132 0.43205309 0.45338294]
 [0.71819581 0.77744362 0.66829804 0.         0.31823114 0.94338865
  0.96925531 0.2421944  0.79625244 0.73799614]
 [1.00703983 0.88769938 0.83388421 0.31823114 0.         1.09306037
  1.20585104 0.55574031 0.7905373  1.02077988]
 [0.61249807 0.22558968 0.2751683  0.94338865 1.09306037 0.
  0.37002762 0.82943775 0.50534774 0.57659959]
 [0.36455136 0.52223785 0.42789747 0.96925531 1.20585104 0.37002762
  0.         0.77729801 0.82483084 0.32394838]
 [0.48786915 0.71179247 0.56430132 0.2421944  0.55574031 0.82943775
  0.77729801 0.         0.8225459  0.51230262]
 [0.90168744 0.30288854 0.43205309 0.79625244 0.7905373  0.50534774
  0.82483084 0.822545

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [882]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[93 28 60 33 27 56 46 55 20 59]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [881]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\2000409876.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [880]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [879]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [878]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [872]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)


[[-0.20017527  0.53212795  0.09869612 -0.396878   -0.17562609 -0.05071748
  -0.36048479  0.21666323 -0.1699652   0.50635953]
 [ 0.04772098  0.32287225 -0.0536505  -0.18783    -0.27184216  0.48832052
   0.13548479  0.17156074 -0.29385871 -0.35877792]
 [ 0.08368679 -0.24416761  0.30143691 -0.53094215  0.07023692 -0.10829887
   0.28187287  0.04928899  0.38919841 -0.29231227]
 [-0.0717143   0.31111835  0.30394907 -0.22280348  0.18864443  0.00369386
  -0.37571406  0.41141515 -0.4392902  -0.1092988 ]
 [ 0.39402329  0.26448833 -0.102241    0.17093031 -0.10231347  0.24785433
  -0.2941198  -0.08502293 -0.31142581 -0.18217326]]


#### 59. How to sort an array by the nth column? (★★☆)

In [861]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 7 2]
 [1 0 0]
 [9 2 8]]
[[1 0 0]
 [9 2 8]
 [8 7 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [860]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [857]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4662620429114238


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [842]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [834]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [830]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 2. 2. 4. 3. 3. 4. 4. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [829]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [828]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [819]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[51 48 58 68]
 [63 47 42 51]
 [50 69 57 42]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [816]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50967603 0.52329347 0.71711311 0.53182787 0.62358321 0.39449346
 0.71921526 0.65756513 0.49678662 0.5826933 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [809]:
a = np.random.randint(0,3,(5,5))
print(a)
b = np.random.randint(0,3,(5,5))
print(b)

np.diag(np.dot(a, b))

[[2 0 1 0 1]
 [1 0 2 1 2]
 [2 1 0 2 0]
 [0 0 2 0 2]
 [0 2 1 2 0]]
[[0 2 2 1 2]
 [2 0 2 2 2]
 [1 2 1 0 1]
 [1 2 0 1 0]
 [2 1 2 0 0]]


array([ 3, 10,  6,  0,  5])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [798]:
a = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(a) + (len(a)-1)*(nz))
Z0[::nz+1] = a
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [790]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [782]:
A = np.arange(36).reshape(6,6)
A[[1,2]] = A[[2,1]]
print(A)

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [771]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 32) ( 0, 49) ( 6, 17) ( 6, 20) ( 7, 70) ( 7, 78) (13, 27) (13, 88)
 (17, 20) (21, 81) (21, 93) (26, 56) (26, 97) (27, 88) (28, 67) (28, 87)
 (29, 67) (29, 88) (32, 49) (39, 50) (39, 87) (50, 87) (56, 97) (62, 95)
 (62, 98) (67, 87) (67, 88) (70, 78) (81, 93) (95, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [766]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [764]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [763]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [762]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.05509234,  0.85722924,  0.91907938,  0.9566443 , -0.50986835,
        0.86775468, -0.24740842,  0.32462623, -0.38824184, -0.74838947,
        0.67354103,  0.30898984, -0.97617423,  0.43128038, -0.62303685,
       -0.51448896, -0.98931132, -0.97734712,  0.61713227,  0.27003688,
        0.35925033, -0.1900908 ,  0.87271791,  0.17741584,  0.93304897,
        0.44507759,  0.89787421, -0.20726752,  0.05310313,  0.47196505,
        0.92286847, -0.23083498, -0.12212007, -0.51083005,  0.15367785,
       -0.95679378, -0.25021448, -0.3882176 , -0.92489929,  0.46187103,
       -0.65506078,  0.54484428,  0.66589521, -0.93935548,  0.06932966,
        0.3448493 , -0.86948504, -0.09259484, -0.93880103, -0.52117924,
        0.52761939, -0.9092826 ,  0.69176278,  0.36468558,  0.82511603,
        0.2438367 ,  0.03436373, -0.98786348, -0.58403025,  0.23287248,
        0.90543582, -0.69106709,  0.26139115,  0.27729338, -0.06152434,
        0.37918493,  0.3135146 , -0.64495659, -0.50297458,  0.40

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [760]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.45979963 10.25222685  7.68139569  3.56331601  6.26740569  0.99940879
  4.40399533  3.72195164  3.43530159  8.2903501 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [761]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.36059286  0.88597225  8.33169873  1.75363991  3.81276911  7.61428764
   2.2442135   0.38290708  3.56074207  9.58962922]
 [ 8.4375443   2.67605597 12.64724782  2.40423272  4.5672209   8.96248448
   3.1568817   1.02570681  6.59901255 14.96981468]
 [ 2.9813657   6.53133734  9.86141392  9.65567579  3.99311889  0.4717883
   4.28176945  5.68810878  7.51078798  7.66813554]
 [11.27844209  9.63550008  0.96538822  1.76004069 12.92596833 16.10099532
   8.62317675 10.82859675  6.80623772  3.09147616]
 [ 6.98908233  4.77307515 14.32017282  1.39068752  2.59906495  7.08710648
   4.1439977   3.13189862  8.58129537 15.98339915]
 [ 4.13118773  7.91326164 10.83312885 10.55102063  5.40034878  1.8411746
   3.83765389  7.0937037   8.75615437  8.13166337]
 [ 9.55182209  4.28587811  4.62009566  1.46678546  9.01612365 12.66265464
   4.02465598  5.63323826  1.13498681  7.73766577]
 [ 5.49512743  2.42841224  4.24514109  2.66101728  5.70729461  9.10513023
   6.08158197  3.51731171  0.24476722  5.73215953]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [754]:
a = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=a.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(a.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = a[z]
print(a)
print(R)

[[4 4 6 8 7 2 4 4 4 3]
 [5 7 6 8 6 5 5 7 4 0]
 [8 3 9 7 1 0 4 1 2 0]
 [2 8 8 1 4 8 5 6 4 6]
 [0 1 6 5 1 0 2 7 0 7]
 [5 8 7 7 3 4 3 9 0 2]
 [8 1 6 3 9 9 7 3 6 4]
 [9 7 4 5 1 5 0 5 1 5]
 [2 0 8 0 9 7 0 7 2 3]
 [1 8 6 3 2 1 6 0 6 3]]
[[0 0 0 0 0]
 [0 4 4 6 8]
 [0 5 7 6 8]
 [0 8 3 9 7]
 [0 2 8 8 1]]


C:\Users\mahen\AppData\Local\Temp\ipykernel_22368\2808035011.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = a[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [755]:

a = np.arange(1, 15)
a.shape
s=sliding_window_view(a,4)
print(s)

NameError: name 'sliding_window_view' is not defined

#### 82. Compute a matrix rank (★★★)

In [713]:
Z = np.random.randint(0,5,(10,10))

rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [701]:
a=np.random.randint(0,10,10)
print(np.bincount(a).argmax())


4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [681]:

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  8  3  5 17]
 [ 8  6 17 12 10]
 [ 3 17  3 42  0]
 [ 5 12 42  2 14]
 [17 10  0 14  3]]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [680]:

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 10 11  6 14]
 [10  5  7  8  9]
 [11  7  7 42 14]
 [ 6  8 42  2 10]
 [14  9 14 10  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [679]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [678]:
a=np.ones((16,16))
k=4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[ 4  0  0  2  3  1  2  0  0  4  0  0  0]
 [ 0  0  0  0  2  4  3  0  0  0  2  0  0]
 [ 0  0  0  0  0  1  1  1  0  1  9  0  0]
 [ 0  4  1  1  0  0  2  3  3  0  0  0  0]
 [ 0  0  1  1  2  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  1  2  0  0  0  0  0  0  3  0]
 [ 2  0  0  3  3  0  0  0  0  0  3  2  1]
 [ 0  0  0  1  4  1  0  0  0  0  1  3  0]
 [ 0  0  1  5 11  1  4  2  0  0  3  4  0]
 [ 0  0  0  0  1  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [673]:
def iterate(a):
    # Count neighbours
    N = (a[0:-2,0:-2] + a[0:-2,1:-1] + a[0:-2,2:] +
         a[1:-1,0:-2]                + a[1:-1,2:] +
         a[2:  ,0:-2] + a[2:  ,1:-1] + a[2:  ,2:])

    # Apply rules
    birth = (N==3) & (a[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (a[1:-1,1:-1]==1)
    a[...] = 0
    a[1:-1,1:-1][birth | survive] = 1
    return a

a = np.random.randint(0,2,(50,50))
for i in range(100): a = iterate(a)
print(a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [669]:
a = np.arange(10000)
np.random.shuffle(a)
print (a[np.argsort(a)[-5:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [644]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [642]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [641]:
a = np.random.rand(int(5e7))

%timeit np.power(a,3)
%timeit a*a*a
%timeit np.einsum('i,i,i->i',a,a,a)

1.12 s ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
236 ms ± 16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
160 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [638]:
a = np.random.randint(0,10,(8,3))
print(a)
b = np.random.randint(0,5,(2,2))
print(b)

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[[7 8 7]
 [6 8 7]
 [1 0 0]
 [3 6 6]
 [1 8 4]
 [5 6 2]
 [6 5 3]
 [2 1 5]]
[[2 0]
 [2 0]]
[2 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [625]:
a = np.random.randint(0,5,(10,3))
print(a)

E = np.logical_and.reduce(a[:,1:] == a[:,:-1], axis=1)

U = a[~E]

print(U)

[[0 2 3]
 [2 1 3]
 [1 4 0]
 [1 4 0]
 [2 0 0]
 [0 1 3]
 [3 2 4]
 [2 2 1]
 [3 2 2]
 [1 2 1]]
[[0 2 3]
 [2 1 3]
 [1 4 0]
 [1 4 0]
 [2 0 0]
 [0 1 3]
 [3 2 4]
 [2 2 1]
 [3 2 2]
 [1 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [624]:
a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [616]:
uZ = np.unique(Z, axis=0)
print(uZ)

[((0., 0.), (0., 0., 0.))]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [612]:
a = np.random.randint(0,5,5)
print(a)
b = np.random.randint(0,5,5)
print(b)
np.einsum('i->', a)       # np.sum(a)
np.einsum('i,i->i', a, b) # a * b
np.einsum('i,i', a, b)    # np.inner(a, b)
np.einsum('i,j->ij', a, b)    # np.outer(a, b)

[2 1 1 1 3]
[2 2 0 2 4]


array([[ 4,  4,  0,  4,  8],
       [ 2,  2,  0,  2,  4],
       [ 2,  2,  0,  2,  4],
       [ 2,  2,  0,  2,  4],
       [ 6,  6,  0,  6, 12]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [592]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [586]:
a = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
b = np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
b &= (a.sum(axis=-1) == n)
print(a[b])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [572]:
a = np.random.randn(100)
n = 1000
idx = np.random.randint(0, a.size, (n, a.size))
means = a[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22339784  0.19707566]
